# Generated by Django 4.0.2 on 2022-03-12 02:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('created', models.DateTimeField(default=datetime.datetime(2022, 3, 12, 2, 42, 27, 755044, tzinfo=utc))),
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('driver_name', models.CharField(blank=True, default='', max_length=100)),
                ('init_load', models.DecimalField(decimal_places=2, max_digits=6)),
                ('init_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('init_km', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fin_load', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fin_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fin_km', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.BooleanField(default=True)),
                ('cause', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
