# Generated by Django 4.0.2 on 2022-02-20 03:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('created', models.DateTimeField(default=datetime.datetime(2022, 2, 19, 22, 14, 50, 76824))),
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('driver_name', models.CharField(blank=True, default='', max_length=100)),
                ('init_load', models.DecimalField(decimal_places=2, max_digits=6)),
                ('init_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('init_km', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fin_load', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fin_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fin_km', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.BooleanField(default=True)),
                ('cause', models.TextField()),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
